extends Node2D

@export var light1: Sprite2D
@export var light2: Sprite2D
@export var light3: Sprite2D
@export var light4: Sprite2D


# Called when the node enters the scene tree for the first time.
func _ready():
	light1.visible = false
	light2.visible = false
	light3.visible = false
	light4.visible = false


func _process(_delta):
	light1.visible = Input.is_action_pressed("BTN_1")
	light2.visible = Input.is_action_pressed("BTN_2")
	light3.visible = Input.is_action_pressed("BTN_3")
	light4.visible = Input.is_action_pressed("BTN_4")
