extends TextureRect

@onready var manager = $"../GameManager"
@export var press: bool = false
@export var hold: bool = false
@export var shake: bool = false
@export var checkpos: int = 0
# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	if press:
		if manager.current_event.press_ok[checkpos] == true:
			visible = false
	if hold:
		if manager.current_event.hold_ok[checkpos] == true:
			visible = false
		else:
			visible = true
	if shake:
		if manager.current_event.shake_ok[checkpos] <= 0:
			visible = false
